[package]
name = "checkmate"
version = "0.12.0"
edition = "2021"

[workspace]

[dependencies]
chess-core = { path = "../../core" }
risc0-zkvm = { version = "1.0", default-features = false, features = ["std"] }
shakmaty = "0.22"
